### ISSUE TITLE
Enabling sound on Linux with pipewire over bluetooth

### ISSUE THREAD

**Issue by wujekbrezniew** [nikp123/scrcpy-desktop#15]
If you have pipewire installed and enabled you can pass audio over bluetooth from phone to pipewire backend on pc.

Simply connect your phone to pc via bluetooth and check if you can pass audio from device to pipewire backend. Phone will detect pipewire server as bluetooth speaker set and pass it directly to your pc speakers. You can even perform calls as pipewire grabs pc mic and sends it to device!

Below quick example of how it works:
https://github.com/nikp123/scrcpy-desktop/assets/11708702/b562be27-a800-43ed-9a48-5ab175560ac6

**Comment by nikp123** [comment]
Neat trick. Though doesn't scrcpy offer that functionality natively over USB in the more recent versions? Haven't updated because I hadn't been working on this for a while. If that still doesn't exist, then this should still work (albeit with its UX issues).

**Comment by nikp123** [comment]
Audio works straight out of the box now, you just need to update your scrcpy version.
