### ISSUE TITLE
display is deprecated

### ISSUE THREAD

**Issue by Bahtiyar57** [nikp123/scrcpy-desktop#17]
![Screenshot 2024-01-14 235418](https://github.com/nikp123/scrcpy-desktop/assets/149698039/55d76d43-993d-4c3c-85d3-1e4484ae2421)

**Comment by nikp123** [comment]
@Bahtiyar57 Thanks for reporting, please check if the update fixed the issue. I couldn't test myself because I am busy with something ATM.

**Comment by nikp123** [comment]
Anyway I think this should be resolved for you, so I'm closing the issue. If there are any further problems, let me know
