### ISSUE TITLE
Null Keyboard alternative in Play Store

### ISSUE THREAD

**Issue by Disonantemus** [nikp123/scrcpy-desktop#18]
[No Keyboard: Hideable keyboard](https://play.google.com/store/apps/details?id=io.github.visnkmr.nokeyboard)

- Seems to the same or better
- Play Store: Available
- Updated: 202401 (Last)
- Size: Very small
- Permissions: None
- Free no IAP

**Comment by nikp123** [comment]
>     * Permissions: None

![image](https://github.com/nikp123/scrcpy-desktop/assets/4696350/6704df28-21d7-4eed-9a3e-ecd9ac91b8b0)
Doesn't seem to be *quite* true, but this may be just Play Store being paranoid. Can you verify on your device that it doesn't give you permission prompts?

**Comment by Disonantemus** [comment]
My mistake with permissions

**Comment by nikp123** [comment]
[It's propriatery but at least it has a discussion repo in case something's up](https://github.com/visnkmr/nokeyboard)

**Comment by nikp123** [comment]
oh yeah i completely forgot about this, i should change the readme as well
![image](https://github.com/nikp123/scrcpy-desktop/assets/4696350/d22e633d-7be5-45ab-ab6a-88951af27dd2)

**Comment by nikp123** [comment]
Closing as Null Keyboard is merely a workaround in case scrcpy's ``-K`` parameter doesn't work out of the box.

**Comment by Disonantemus** [comment]
Maybe you can have that as an option, because there are many different international keyboards that can be trouble. Is good 2 have options, if it's not too complex.

I was testing **Termux** with **Scrcpy** in fullscreen and get here, for that use case I did a very small script, almost a 1-liner:
~~~
#!/bin/bash
adb shell wm size 1920x1080
scrcpy --stay-awake --window-borderless --fullscreen 
echo -e "\n- Returning to default resolution:"
adb shell wm size reset
adb shell wm size
~~~

In Termux I do:
- `Volume`+q (virtual keyboard) to hide **Extra Keys**.
- `Alt+b` (hardware keyboard), to hide virtual keyboard.

This works 4 me, but, I use an international keyboard and works only like an US keyboard, I did try `--hid-keyboard` and didn't work. In other apps, works as should.

**Comment by nikp123** [comment]
Oh you mean like the ``-K`` parameter only passes through the US layout onto the target device?

**Comment by nikp123** [comment]
Perhaps you'll like this behavior instead: On startup it checks for *No Keyboard*, if it's present it will use it. Please let me know if that's what you want.

**Comment by Disonantemus** [comment]
It's ok, 4 now I'm using my mini script.
