### ISSUE TITLE
Cannot get it to work

### ISSUE THREAD

**Issue by erzurum2525** [nikp123/scrcpy-desktop#21]
done everything and downloaded taskbar but when I run the script with this command
.\startscreen.ps1 -Resolution 1920x1080 -DPI 200
It shows my phone screen instead of desktop mode

**Comment by erzurum2525** [comment]
![image](https://github.com/user-attachments/assets/a4849d98-cd74-4adb-ba10-26ec43b0b363)
this is image from PC scrcpy

**Comment by nikp123** [comment]
> ![image](https://private-user-images.githubusercontent.com/183532562/375817397-a4849d98-cd74-4adb-ba10-26ec43b0b363.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4NTUyNTcsIm5iZiI6MTcyODg1NDk1NywicGF0aCI6Ii8xODM1MzI1NjIvMzc1ODE3Mzk3LWE0ODQ5ZDk4LWNkNzQtNGFkYi1iYTEwLTI2ZWM0M2IwYjM2My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QyMTI5MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NzI0ZTZhMGRkNmMwZGM0ZTI4YTk5YjZhNDExNTFmMTExNTVlNzM1ZDgzZjFkZjgzMTdkZDUzMDdhNWU2MWQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.51cJFSfKDMwRahiD9Vo7aGlUgz5V6joHqpu2q-DnKZc) 

Can you explain what the error message is in the window on top of your phones screen? 

Also if you don't mind sharing the logs from the cmd window, as that would help a lot.

**Comment by erzurum2525** [comment]
It doesnt show an error 
edit: my device makes random numbers instead of displayID 1 everytime such as 22 and 17 so I solved it by typing the displayID manually

**Comment by erzurum2525** [comment]
thanks!
