### ISSUE TITLE
Android 9?

### ISSUE THREAD

**Issue by N1NJ4** [nikp123/scrcpy-desktop#6]
Feature request: Able to get it to run for android 9?
Could open it up for other previous versions as i do note that 10 had some changes that causes problems with backwards compatibility...or something.

**Comment by nikp123** [comment]
Very much, no. This is because this feature was introduced in Android 10.

You could try doing ``wm size your_monitor_resolution`` and ``wm density your_dpi`` but you'll ALMOST CERTAINLY end up with an unusable phone, which is why it's 10 times better to do it this way. Sorry.
