### ISSUE TITLE
Black screen in scrcpy

### ISSUE THREAD

**Issue by patientx** [nikp123/scrcpy-desktop#7]
Sorry for the question if it seems stupid but, do these binutils something that only those "usable as desktop"  phones such as those samsungs etc or are they an installable package maybe requiring root ?

**Comment by Underknowledge** [comment]
coming from here https://github.com/nikp123/scrcpy-desktop/issues/8#issuecomment-946403808
I have a stock OnePlus5 Cheeseburger and faced the same issue. 
after installing com.farmerbb.taskbar I got it running. only enabling display over other apps.
Adding this to the readme isn't terrible.

**Comment by nikp123** [comment]
did so

**Comment by nikp123** [comment]
Closing this as it seems to be addressed in the current version of scrcpy-desktop? I think...
